Awesome books: plain JavaScript with objects
brainskev/Awesome-books pull request #1
Opened 2022-11-29 13:30 UTC by Mutai-Gilbert

In this pull request we were able to:
- Understand how to use medium-fidelity wireframes to create a UI.
-  Understand different ways to create objects in JavaScript.
- Create and access properties and methods of JavaScript objects.

2022-11-29 18:18 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi team 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Used GitHub Flow
✔️ No linter errors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Please consider adding a license to your project as it is advisable for every software (opensource included) to have a license 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-29 18:18 UTC, codepantha commented on modules/store.js
> +  }
- [ ] I noticed a small bug 🐛 where if you delete a book, its element gets removed from the DOM but the book still exists in `localStorage` so when you reload the page, the book appears again. Please try to fix this in order to get approved 👍

2022-11-30 08:49 UTC, jerryowusu approved these changes
Hi  Team :wave: , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![kpop-approved](https://user-images.githubusercontent.com/65233860/204750001-8d8e57b1-9363-4f81-ad86-589a56eaf5c9.gif)


## Highlights
All linters are working well :100: 
Well documented readme :+1: 
Used GitHub Flow :1st_place_medal: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-30 08:49 UTC, jerryowusu commented on README.md
> +This project is [MIT](./MIT.md) licensed.
[OPTIONAL] Kindly fix the link to the license since it is not working properly. :pray:

2022-11-30 08:50 UTC, merged

2022-11-30 09:29 UTC, Bondok6 commented
## Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, which is already approved, this project is a [pair-programming project](https://github.com/microverseinc/curriculum-javascript/blob/main/books/m1_plain_js_objects.md#:~:text=Work%20and%20submission%20mode,of%20your%20pair%2Dprogramming%20group.) so only one student should request a review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._